# -*- coding: utf-8 -*-
"""fase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNKP_xfCmmdBYUOvb_6h17di7XC9Yz4W

Import das libs
"""

#manipulação dos dados
import pandas as pd
import numpy as np

#visualização dos dados
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

"""Leitura dos dados"""

#dados dos clientes
arq_clientes = pd.read_csv('/content/olist_customers_dataset.csv')
df_clientes = pd.DataFrame(arq_clientes)

#dados de geolocalização
arq_geolocalizacao = pd.read_csv('/content/olist_geolocation_dataset.csv')
df_geolocalizacao = pd.DataFrame(arq_geolocalizacao)

#dados do pedido - itens
arq_itens = pd.read_csv('/content/olist_order_items_dataset.csv')
df_itens = pd.DataFrame(arq_itens)

#dados de pagamentos dos pedidos
arq_pagamentos = pd.read_csv('/content/olist_order_payments_dataset.csv')
df_pagamentos = pd.DataFrame(arq_pagamentos)

#dados de avaliações
arq_avaliacoes = pd.read_csv('/content/olist_order_reviews_dataset.csv')
df_avaliacoes = pd.DataFrame(arq_avaliacoes)

#dados dos pedidos
arq_pedidos = pd.read_csv('/content/olist_orders_dataset.csv')
df_pedidos = pd.DataFrame(arq_pedidos)

#dados dos produtos
arq_produtos = pd.read_csv('/content/olist_products_dataset.csv')
df_produtos = pd.DataFrame(arq_produtos)

#dados dos lojistas
arq_lojistas = pd.read_csv('/content/olist_sellers_dataset.csv')
df_lojistas = pd.DataFrame(arq_lojistas)

#tradução dos produtos
arq_traducao = pd.read_csv('/content/product_category_name_translation.csv')
df_traducao = pd.DataFrame(arq_traducao)

"""Preparação de tabela analítica"""

#Deduplicando linhas da tabela para não gerar duplicidade no cruzamento

#Considera primeira forma de pagamento
df_pagamentos_agrupado = df_pagamentos.groupby('order_id').agg(
    forma_pagamento = ('payment_type', 'first')
)

#Aplica nota média
df_avaliacoes_agrupado = df_avaliacoes.groupby('order_id').agg(
    nota_media = ('review_score', 'mean')
)

df_avaliacoes_agrupado['nota_media'] = df_avaliacoes_agrupado['nota_media'].round(0)

#Marca nome da categoria e formas de pagamento
merged_df = df_itens.merge(
    df_produtos,
    how = 'left',
    on = 'product_id'
).merge(
    df_pagamentos_agrupado,
    how = 'left',
    on = 'order_id'
).merge(
    df_avaliacoes_agrupado,
    how = 'left',
    on = 'order_id'
).merge(
    df_lojistas,
    how = 'left',
    on = 'seller_id'
).merge(
    df_pedidos,
    how = 'left',
    on = 'order_id'
)

#Verifica se houve duplicidade contando as linhas da tabela inicial e enriquecida
print(len(df_itens))
print(len(merged_df))

"""Insights

1. Crescimento da receita:O marketplace apresenta crescimento relevante no volume de pedidos, indicando aumento da base de clientes e adoção da plataforma
"""

merged_df['order_approved_at'] = pd.to_datetime(merged_df['order_approved_at'])
merged_df['mes_referencia'] = merged_df['order_approved_at'].dt.strftime('%m-%Y')
merged_df['ano_referencia'] = merged_df['order_approved_at'].dt.strftime('%Y')

crescimento_periodo = merged_df.groupby(
    'ano_referencia'
).agg(
    receita = ('price', 'sum'),
    qtd_pedidos = ('order_id', 'count')
).reset_index()

# Criando o gráfico de linhas
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(crescimento_periodo['ano_referencia'], crescimento_periodo['receita'], marker='o', color='skyblue')

# Adicionando rótulos de dados
for i, row in crescimento_periodo.iterrows():
    ax.text(row['ano_referencia'], row['receita'] + 100000, f'R${row['receita']:,.2f}', ha='center', va='bottom', rotation=45)

plt.title("Evolução da Receita")
plt.xlabel("Ano")
plt.ylabel("Receita")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""2. Apesar do crescimento, o comportamento de compra mostra baixo volume por pedido, sugerindo oportunidade de aumento de ticket médio"""

media_qtd_pedidos = merged_df.groupby(
    ['ano_referencia','order_id']
).agg(
    total_items_count = ('order_id', 'count')
)


media_qtd_pedidos_agrupado = media_qtd_pedidos.groupby(
    'ano_referencia'
).agg(
    media_itens = ('total_items_count', 'mean')
).reset_index()

media_qtd_pedidos_agrupado['media_itens'] = media_qtd_pedidos_agrupado['media_itens'].round(0)

media_qtd_pedidos_agrupado.plot(x='ano_referencia', y='media_itens', figsize=(10, 6))
plt.title("Evolução da média de itens por pedido")
plt.xlabel("Ano")
plt.ylabel("Qtd de Itens por Pedido")

"""3. O uso predominante de cartão de crédito, especialmente em compras parceladas, está associado a tickets mais altos, indicando potencial para estratégias de incentivo."""

tipo_pagamento = merged_df.groupby(
    'forma_pagamento'
).agg(
    qtd_pedidos = ('order_id', 'nunique')
).reset_index()

tipo_pagamento.plot(x='forma_pagamento', y='qtd_pedidos', kind='bar', figsize=(10, 6))
plt.title("Quantidade de Pedidos por Forma de Pagamento")
plt.xlabel("Forma de Pagamento")
plt.ylabel("Quantidade de Pedidos")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

#Mapeamento de categorias mais vendidas
categorias_vendas = merged_df.groupby(
    'product_category_name'
).agg(
    qtd_pedidos = ('order_id', 'nunique'),
    receita = ('price', 'sum')
)

categorias_vendas = categorias_vendas.sort_values(by='receita', ascending=False)

categorias_vendas_top = categorias_vendas.head(10)

categorias_vendas_top = categorias_vendas_top.reset_index()
categorias_vendas_top.rename(columns={'product_category_name': 'categorias_produto'}, inplace=True)

categorias_vendas_top

"""4. A experiência do cliente é polarizada: enquanto muitos pedidos recebem avaliações máximas, há uma parcela significativa de experiências negativas"""

qtd_avaliacoes = merged_df.groupby(
    'nota_media'
).agg(
    qtd_pedidos = ('order_id', 'nunique')
).reset_index()


qtd_avaliacoes.plot(x='nota_media', y='qtd_pedidos', kind='bar', figsize=(10, 6))
plt.title("Quantidade de pedidos por avaliação")
plt.xlabel("Avaliação")
plt.ylabel("Quantidade de Pedidos")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

"""5. A análise revela que atrasos na entrega são o principal fator associado a avaliações negativas, indicando gargalos logísticos."""

merged_df['dias_entrega'] = pd.to_datetime(merged_df['order_delivered_customer_date']) - pd.to_datetime(merged_df['order_purchase_timestamp'])
merged_df['dias_atraso'] = pd.to_datetime(merged_df['order_delivered_customer_date']) - pd.to_datetime(merged_df['order_estimated_delivery_date'])
merged_df['status_entrega'] = np.where(
    merged_df['dias_atraso'] > pd.Timedelta(0), 'Atraso',
    'No prazo'
)
merged_df['dias_atraso'] = merged_df['dias_atraso'].dt.days


condicoes = [
    (merged_df['dias_atraso'] <= 5),
    (merged_df['dias_atraso'] > 5) & (merged_df['dias_atraso'] <= 15),
    (merged_df['dias_atraso'] > 15) & (merged_df['dias_atraso'] <= 30),
    (merged_df['dias_atraso'] > 30)
]
faixas = ['0-5 dias', '6-15 dias', '16-30 dias', 'mais de 30 dias']
merged_df['faixa_atraso'] = np.select(condicoes, faixas, default='N/A')


atraso_avaliacoes = merged_df.groupby(
   ['nota_media', 'status_entrega']
).agg(
  qtd_pedidos = (
      'order_id',
      'nunique'
  )
).reset_index()

fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(
    data=atraso_avaliacoes,
    x='nota_media',
    y='qtd_pedidos',
    hue='status_entrega',
    ax=ax
)
plt.title("Quantidade de Pedidos por Avaliação e Status de Entrega")
plt.xlabel("Avaliação Média")
plt.ylabel("Quantidade de Pedidos")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""6. O marketplace apresenta alta concentração de vendas em uma única região, o que representa risco operacional e dependência."""

qtd_vendas_lojistas = merged_df.groupby(
    'seller_state'
).agg(
    qtd_pedidos = ('order_id', 'nunique'),
    receita = ('price', 'sum')
)

qtd_vendas_lojistas = qtd_vendas_lojistas.sort_values(by='receita', ascending=False)

qtd_vendas_lojistas.head(5).plot(kind='pie', y='receita', autopct='%1.1f%%', figsize=(6, 8))
plt.title("Receita por Região")

"""7. Categorias com alto volume nem sempre entregam boa experiência, indicando oportunidades de curadoria ou melhoria de qualidade."""

categorias_vendas_avaliacao = merged_df[merged_df['nota_media'] < 4.0].groupby(
    ['product_category_name', 'nota_media']
).agg(
    qtd_pedidos = ('order_id', 'nunique'),
    receita = ('price', 'sum')
)

categorias_vendas_avaliacao = categorias_vendas_avaliacao.sort_values(by='qtd_pedidos', ascending=False)

categorias_vendas_avaliacao_top = categorias_vendas_avaliacao.head(10)

categorias_vendas_avaliacao_top = categorias_vendas_avaliacao_top.reset_index()
categorias_vendas_avaliacao_top.rename(columns={'product_category_name': 'categorias_produto'}, inplace=True)
categorias_vendas_avaliacao_top['nota_media'] = categorias_vendas_avaliacao_top['nota_media'].astype(int)

pivot_table_categorias_avaliacoes = pd.pivot_table(
    categorias_vendas_avaliacao_top,
    values=['qtd_pedidos','receita'],
    index='categorias_produto',
    columns='nota_media',
    aggfunc='sum',
    fill_value=0
).style.format({
    ('receita', 1.0): "R${:,.2f}",
    ('receita', 3.0): "R${:,.2f}"
})
display(pivot_table_categorias_avaliacoes)